### ISSUE TITLE
Make `Diag` structure within FV3GFS_io.F90 public?

### ISSUE THREAD

**Issue by spencerkclark** [NOAA-GFDL/SHiELD_physics#29]
In [AI2's Python-wrapped version of FV3GFS](https://github.com/ai2cm/fv3gfs-fortran/tree/master/FV3/wrapper), we have some functionality that enables getting the values of physics diagnostics.  While it can be a little dangerous (e.g. I would not recommend getting the values of physics diagnostics that are accumulated) this functionality can be useful for some purposes, including testing some override capabilities (e.g. prescribing surface radiative fluxes or the sea surface temperature from the wrapper).

This feature requires access to the [`Diag`](https://github.com/NOAA-GFDL/SHiELD_physics/blob/0ff11e85972c48057f8d4d5f08322d9fdc0fb7f2/FV3GFS/FV3GFS_io.F90#L149C51-L149C51) data structure in the `FV3GFS_io.F90` module, which is an array of [`gfdl_diag_type`](https://github.com/NOAA-GFDL/SHiELD_physics/blob/0ff11e85972c48057f8d4d5f08322d9fdc0fb7f2/FV3GFS/FV3GFS_io.F90#L115-L143) structures that contain metadata and pointers to the data for the main physics diagnostics of the model.  In SHiELD, this data structure (as well as its internal attributes) are not tagged as `public`.  Would we be open to making this data structure `public` in SHiELD, so that I can implement similar functionality for the Python-wrapped version of SHiELD?

**Comment by lharris4** [comment]
Hi, Spencer. I am in favor of this change. Given the nature of SHiELD I think it is OK to just make the data structure a public object rather than go to the work of creating an API of getters and setters. (We could place a label on it: ``No user serviceable parts inside''.)

I will defer to @bensonr @laurenchilutti @linjiongzhou as to whether this is the best approach but I am in favor of it.

Thanks
Lucas

**Comment by bensonr** [comment]
@spencerkclark - I haven't looked at the code in quite a few years, but the FV3GFS_io.F90 Diag type should be aliased to the IPD_Diag and available at the atmos_model_mod (atmos_model.F90) level of the model.

**Comment by spencerkclark** [comment]
Thanks @bensonr.  This is indeed the case in our old fork of FV3GFS (which is how we've set things up there), but in SHiELD I think `FV3GFS_io.Diag` is (somewhat confusingly) separate from `atmos_model_mod.IPD_Diag`.  `atmos_model_mod.IPD_Diag` is populated in [`physics_diag_layer.diag_populate`](https://github.com/NOAA-GFDL/SHiELD_physics/blob/0ff11e85972c48057f8d4d5f08322d9fdc0fb7f2/GFS_layer/GFS_diagnostics.F90#L28-L3459), while `FV3GFS_io_mod.Diag` is populated in [`FV3GFS_io_mod.gfdl_diag_register`](https://github.com/NOAA-GFDL/SHiELD_physics/blob/0ff11e85972c48057f8d4d5f08322d9fdc0fb7f2/FV3GFS/FV3GFS_io.F90#L3024-L6867), and these two data structures are not populated with the same data.

`FV3GFS_io.Diag` is what is actually used in writing out diagnostics in [`FV3GFS_io.gfdl_diag_output`](https://github.com/NOAA-GFDL/SHiELD_physics/blob/0ff11e85972c48057f8d4d5f08322d9fdc0fb7f2/FV3GFS/FV3GFS_io.F90#L7030-L7430).  Conversely, while it gets populated in the [`IPD_initialize`](https://github.com/NOAA-GFDL/SHiELD_physics/blob/0ff11e85972c48057f8d4d5f08322d9fdc0fb7f2/IPD_layer/IPD_driver.F90#L44-L71) routine, I'm not sure if `atmos_model_mod.IPD_Diag` ever ends up being used for anything meaningful within SHiELD.  

I'm guessing there is a story behind this that I am not familiar with.

**Comment by linjiongzhou** [comment]
I'm just a user of these functions, so I'll leave it to Rusty and Lauren to determine the most suitable approach.

Linjiong

**Comment by lharris4** [comment]
It's a little challenging to tease out the abstractions here. This `IPD_Diag` of `IPD_Diag_type` holds a lot of metadata for each variable, each of which then includes a pointer to data within `Diag` of `intdiag_type` which is an alias of `[GFS_diag_type](https://github.com/NOAA-GFDL/SHiELD_physics/blob/0ff11e85972c48057f8d4d5f08322d9fdc0fb7f2/GFS_layer/GFS_typedefs.F90#L1159)`. The `GFS_diag_type` does not hold metadata, just the individual datasets, whereas IPD_Diag is a generic container which can hold a number of different datasets.

In any case, I believe `IPD_Diag`s are just for I/O and do not control the model state itself, so reading it should be safe as long (as you said) you don't read from a variable which is being accumulated.

All of this should be pretty similar between FV3GFS and the most recent version of SHiELD since the IPD layer has not been heavily modified over the years.

If you wish to actually override data, such as in the surface datasets, that is a different story. I think `[sfcprop_type =>  GFS_sfcprop_type](https://github.com/NOAA-GFDL/SHiELD_physics/blob/0ff11e85972c48057f8d4d5f08322d9fdc0fb7f2/GFS_layer/GFS_abstraction_layer.F90#L7C38-L7C38)` is what you want to modify.

**Comment by spencerkclark** [comment]
> This `IPD_Diag` of `IPD_Diag_type` holds a lot of metadata for each variable, each of which then includes a pointer to data within `Diag` of `intdiag_type` which is an alias of [`GFS_diag_type`](https://github.com/NOAA-GFDL/SHiELD_physics/blob/0ff11e85972c48057f8d4d5f08322d9fdc0fb7f2/GFS_layer/GFS_typedefs.F90#L1159). The `GFS_diag_type` does not hold metadata, just the individual datasets, whereas IPD_Diag is a generic container which can hold a number of different datasets.

Yes, I am familiar with how all of this works.  The point I am bringing up is that in SHiELD there is another (non-identical) version of this metadata infrastructure (including some type definitions) in `FV3GFS_io.F90` ([`Diag`](https://github.com/NOAA-GFDL/SHiELD_physics/blob/0ff11e85972c48057f8d4d5f08322d9fdc0fb7f2/FV3GFS/FV3GFS_io.F90#L149) <-> [`IPD_Diag`](); [`gfdl_diag_type`](https://github.com/NOAA-GFDL/SHiELD_physics/blob/0ff11e85972c48057f8d4d5f08322d9fdc0fb7f2/FV3GFS/FV3GFS_io.F90#L115-L143) <-> [`IPD_diag_type`](https://github.com/NOAA-GFDL/SHiELD_physics/blob/0ff11e85972c48057f8d4d5f08322d9fdc0fb7f2/IPD_layer/IPD_typedefs.F90#L49C21-L64); `Diag` is populated [here](https://github.com/NOAA-GFDL/SHiELD_physics/blob/0ff11e85972c48057f8d4d5f08322d9fdc0fb7f2/FV3GFS/FV3GFS_io.F90#L3024-L6867) <-> `IPD_Diag` is populated [here](https://github.com/NOAA-GFDL/SHiELD_physics/blob/0ff11e85972c48057f8d4d5f08322d9fdc0fb7f2/GFS_layer/GFS_diagnostics.F90#L28-L3459)).  There is overlap between the diagnostics that are defined in `FV3GFS_io.F90` and those that are defined in `GFS_diagnostics.F90`, but they are not the same, and the source of truth for SHiELD is in `Diag` in `FV3GFS_io.F90`, and not `IPD_Diag`.

> If you wish to actually override data, such as in the surface datasets, that is a different story. I think [`sfcprop_type => GFS_sfcprop_type`](https://github.com/NOAA-GFDL/SHiELD_physics/blob/0ff11e85972c48057f8d4d5f08322d9fdc0fb7f2/GFS_layer/GFS_abstraction_layer.F90#L7C38-L7C38) is what you want to modify.

Yes, this is the same as in FV3GFS, and (among other ways) is how we modify variables in the physics, which is enabled by https://github.com/NOAA-GFDL/atmos_drivers/pull/26.  We indeed only care about "getting" data in the case of these  diagnostics fields.

**Comment by spencerkclark** [comment]
Per our discussion today, I went ahead and made a PR to make this change (#30).

**Comment by lharris4** [comment]
Glad we can move forward on this.
